baseurl = "https://robruizr.dev/"
title = "RobRuizR"
theme = "hugo-creative-portfolio-theme"
DefaultContentLanguage = "en"
languageCode = "en"
# Enable comments by entering your Disqus shortname
# disqusShortname = ""
# Enable Google Analytics by entering your tracking code
# googleAnalytics = ""
[languages] 
  [languages.en]
    weight = 1
  [languages.es]
    weight = 2
    
    [languages.es.params]
      # Style options: default (pink), blue, green, pink, red, sea, violet
      # Use custom.css for your custom styling
      description = "Sitio web de RobRuizR"
      copyright = "&copy; RobRuizR"
      sidebarAbout = [
        "Profesor e Ingeniero de Software con 4 años de experiencia en Desarrollo Web",
        "Actualmente viviendo en México."
      ]

      [[languages.es.params.navlinks]]
      name = "Inicio"
      url = "es/portfolio/"
      home = true

      [[languages.es.params.navlinks]]
      name = "Sobre mí"
      url = "es/about/"

      [[languages.es.params.navlinks]]
      name = "Contáctame"
      url = "es/contact/"

      [[languages.es.params.navlinks]]
      name = "English version"
      url = "portfolio/"

      [languages.es.params.contact]
        othersContact = "También puedes encontrarme en"
        formTitle = "¿Platicamos?"
        formName = "Tu nombre"
        formEmail = "Tu correo"
        formMessage = "Tu mensaje para mí"
        formMessageTemplate = [""]

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "violet"
  description = "Describe your website"
  copyright = "&copy; RobRuizR"
  sidebarAbout = [
    "Teacher and Software Engineer with 4 years of experience in Web Development",
    "Currently living in Mexico."
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "xzbkggvw"

    # Optional Matomo analytics (formerly piwik)
      # [params.analytics.matomo]
      #  URL = "https://stats.example.com"
      #  ID = "42"
      #  # Track all subdomains with "*.example.com" (Optional)
      #  domain = "www.example.com"
      #  # Optional integrity check hash
      #  hash = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"

  [[params.navlinks]]
  name = "Get in touch"
  url = "contact/"

  [[params.navlinks]]
  name = "Versión en español"
  url = "es/portfolio/"

  [params.social]
  # email         = "email@example.com"
  twitter       = "https://twitter.com/robruizr"
  github        = "https://github.com/robruizr"

  [params.contact]
    othersContact = "You can find me also on"
    formTitle = "Drop me a line, maybe?"
    formName = "Your name"
    formEmail = "Your email"
    formMessage = "Your message for me"
    formMessageTemplate = [""]


